### ISSUE TITLE
Ability to export/import input prices

### ISSUE THREAD

**Issue by the-cat-is-maybe** [aritchie05/EcoCraftingTool#101]
As a user I wish to be able to share my calculator inputs and results with other people I am playing with.

To make this easier it would be nice to be able to export the locally stored cached data into a text file that I can send to other players.

Then,

As a user I wish to be able to take a text file and upload it to my version of eco-calc to receive the same local data as what was sent to me.

Possible problems/pitfalls:

1. Overwrite all current local data, or overwrite values that are set to 0, or a hybrid. Possible solutions include
  a. Always overwrite all current local data
  b. other options in between such as on import choose overwrite all vs overwrite 0s, vs overwrite overlap
  c. Allow importer to pick and choose values to import

**Comment by Enderswood** [comment]
Hi, we try to make a colony with standardised price, and sharing all price is the key of sucess.

the import/export feature is just critical for us, we can't share the prices for advance ressource without hours of individual settings.... 

import export would allow to saves days of work, and make it so much easy for different play !

Thank you very much :)

**Comment by aritchie05** [comment]
Hi @Enderswood if you want to import/export right now you can copy/paste the values from F12 (dev console) Application -> Local Storage -> https://eco-calc.com

![image](https://github.com/aritchie05/EcoCraftingTool/assets/15224019/cf60b055-0ef9-4316-a45e-e73942117c32)

I am planning to add actual import/export when I have a chance but it will basically just be doing this.

**Comment by Enderswood** [comment]
Would be awesome, I will look at it, F12 is totally fine for me, but I know most of my fellow citizen would feel totally lost lol

**Comment by aritchie05** [comment]
I have implemented this feature with full override of all current data, except for locale.
