### ISSUE TITLE
Suggestion: add an option to only calculate everything when a button is clicked

### ISSUE THREAD

**Issue by KironaDragryph** [aritchie05/EcoCraftingTool#114]
I'm playing a fairly low-population server where many folks do multiple jobs. Trying to check prices on all of it, however, makes the site INCREDIBLY laggy, as everything is re-evaluated with every single change I make.

It would be much easier if I could go through the entire middle column and input prices, and then click "calculate" at the end, instead of it working through the entire set every time I do anything at all.

**Comment by aritchie05** [comment]
I like this idea a lot. App performance is pretty bad
