### ISSUE TITLE
Hunter Skill does not default to allowing entry of a cost of Raw Fish for Dried Fish recipe.  

### ISSUE THREAD

**Issue by sirPattrick** [aritchie05/EcoCraftingTool#117]
I have no idea how the Eco Calc is coming up with a price for Dried Fish, since Raw Fish is not an input, on the Input Column, which is the main issue I am writing about.

**Comment by sirPattrick** [comment]
Unless it is assuming Raw Fish is the same price as Raw meat, which is what it could be doing.

**Comment by aritchie05** [comment]
Raw Fish is not listed under the Inputs section if you have some recipe that produces raw fish in in the Outputs section. Instead, the base price of that raw fish recipe is used (or the lowest base price if you have multiple)

Here's a simple example:
![image](https://github.com/aritchie05/EcoCraftingTool/assets/15224019/5ca4b0d4-652d-40f1-973c-8359d788944f)


If I remove the Raw Fish (Clean Large Fish) recipe, Raw Fish becomes the Input.
![image](https://github.com/aritchie05/EcoCraftingTool/assets/15224019/a0c53883-233f-4945-857b-9e92cb0a76f8)
