### ISSUE TITLE
Machinist specialisation missing Electric Machinist Table

### ISSUE THREAD

**Issue by Dave247** [aritchie05/EcoCraftingTool#18]
When selecting the Machinist spec, the Electric Machinist Table doesn't appear in the list, meaning the related recipes on the table that require Machinist labor also don't appear in the list. Both Glassworking and Industry correctly list the table however.

**Comment by aritchie05** [comment]
Hi @Dave247, I was not able to reproduce this. When I select Mechanics I see Electric Machinist Table with the expected recipes (Copper Wiring, Combustion Engine/Generator, Gold Wiring, etc.) Can you provide any more details?

![image](https://user-images.githubusercontent.com/15224019/132154628-b3c1715c-445e-4a4b-9045-dc87e42f40d3.png)

**Comment by Dave247** [comment]
Ah I think it might of had something to do with how the sites saves the last stored information. I think when I first started using it I might of clicked the cross to remove the Electric Machinist Table from the list so on subsequent times that I returned to the site it would not be there, without me having to completely remove the specialization and re-add it (which would also remove all of the stored pricing data too).

I'm a little confused as I tested it in a incognito window last night and thought I remember not seeing it appear there either, but I might of just been tired and not paying attention properly.

**Comment by aritchie05** [comment]
Thanks for the update. I have encountered that problem for example with mining/smelting, where you don't want to see blast furnace and the higher tier mining machines at the start of the game. To add them later you have to add the recipes manually. I will look into adding some way to perhaps add individual crafting tables or reset all the output recipes to the initial skill added state

**Comment by Dave247** [comment]
> Thanks for the update. I have encountered that problem for example with mining/smelting, where you don't want to see blast furnace and the higher tier mining machines at the start of the game. To add them later you have to add the recipes manually. I will look into adding some way to perhaps add individual crafting tables or reset all the output recipes to the initial skill added state

I actually have recently encountered the same issue with mining and smelting myself in a current cycle. With mining selected and trying to figure out the price of concentrate, due to there being multiple recipes with, some with different item ratios in different tables for the same item the calculator will group them together but always use the lowest/most efficient recipe and value when calculating the price of other produced items, unless you manually remove that table from the list which caused me a fair amount of confusion as to why things were comming out so cheap.
