### ISSUE TITLE
How does it work ?

### ISSUE THREAD

**Issue by AntoninHS** [aritchie05/EcoCraftingTool#34]
Hello, I dont understand at all how it work, I'm trying to figure out how many raw ressources I need to make some crafting table, but it's not clear how I can get this information, is there a tutorial somewhere or am I missing something ?

Here, I'm trying to figure out what I need to make a froth floatation cell for example, But I cant put a 1 in the text field

https://imgur.com/mljBiCC

**Comment by aritchie05** [comment]
@AntoninHS Fundamentally the purpose of the calculator is to compute the production cost of recipes on the right. If you set the input fields to a buy price, it will tell you the total production cost of the floatation cell. If you want to see how much of a material is required for a recipe, you can enter 1 for the price of that input. It's not really designed to be used that way. I could potentially add a hover popup on the outputs that would display the input cost, I think that would be useful
