### ISSUE TITLE
Recipes need to be updated to latest version of game (9.5.2)

### ISSUE THREAD

**Issue by MiniMeowsketeer** [aritchie05/EcoCraftingTool#40]
I have noticed some recipes are outdated or missing. Various furniture recipes are missing. Recurve bow seems to think it takes steel ingots but it currently takes iron ingots, not steel. Have noticed charred mortar recipe seems to be missing, as well as the oil recipe that uses sunflower seeds.

Data should be updated to reflect 9.5.2.

**Comment by rannmann** [comment]
Develop branch has 9.5.2 updates.  Recipes are there but there are some images missing, translations missing, and some minor other issues.  Once these are resolved, main can have updates applied.
