### ISSUE TITLE
Bread and Camas Bread are in Baking, not Adv. Baking

### ISSUE THREAD

**Issue by padmanek** [aritchie05/EcoCraftingTool#41]
Title.
Also, we really need calorie cost upgrade from 9.5.
lvl 1 is 20% calorie reduction and then 5% per lvl until lvl 7 at 50% calorie reduction.

**Comment by rannmann** [comment]
Bread and Camas bread were updated in 432142ca65489d5ec29950b6d05b35a74fa16b4e (develop).
