### ISSUE TITLE
[Develop] Need localization updates for 9.5 items

### ISSUE THREAD

**Issue by rannmann** [aritchie05/EcoCraftingTool#44]
Items Added:

* ElevatorCallPostItem
* FertilizerFiller
* MediumLeatherCarcass
* RawFood
* SmallFish
* SteelSquareFixtureItem
* SunflowerItem

Items Modified:
* CropSeed (nameID changed from `Crop Seed`)

Additionally, there were updates to `Crab Pot` and `Crushed Mixed Rock`, but neither the name nor nameID changed for either of these, so they should be fine.  But it's good to double-check them.

**Comment by aritchie05** [comment]
Fixed with PR #46

**Comment by rannmann** [comment]
Looks good at a glance, but I'll have to check it out later from my other machine to see the whole diff.  I assume most of the updates are due to Google's translation changes?
