### ISSUE TITLE
Locale data is mostly duplicates.

### ISSUE THREAD

**Issue by rannmann** [aritchie05/EcoCraftingTool#45]
The `localeData` definition seems to have 11 arrays in it, and each array contains identical values.  If you open the `locale-data.ts` file and ctrl+f for `AcornItem`, you'll see what I'm talking about.

This file is 8.2MB, so if we can remove the duplicates the file should be reduced to about 0.75MB.

**Comment by aritchie05** [comment]
Not sure how this happened, just fixed. I am about to go through the new items from 9.5 and add translations.

See commit [3db03d9](https://github.com/aritchie05/EcoCraftingTool/commit/3db03d9f1bad82d47d1137db252f0b6d6e211951)
