### ISSUE TITLE
Certain recipes are producing specific items instead of tags as intended

### ISSUE THREAD

**Issue by aritchie05** [aritchie05/EcoCraftingTool#52]
For example, Hewn Logs recipe should produce HewnLog tag rather than the specific item HewnLogItem. This is because there are multiple recipes that use HewnLog tag as an ingredient rather than the specific item (HewnLogItem, SoftwoodHewnLogItem, etc.)

I believe the following items are affected by this, it was accidentally changed when the recipes were updated for 9.5. Any item which produces different variants is probably affected. (e.g. Softwood & Hardwood)

HewnLog
Boards
Lumber
CompositeLumber
AshlarStone

**Comment by aritchie05** [comment]
This causes an issue where the output price is not correctly considered for other recipes. For example, price of BU1 should be automatically considering the output price of Hewn Logs here, but it is not because the HewnLogs recipe output is HewnLogItem, rather than HewnLog (tag). And the BU1 recipe uses HewnLog (tag) as ingredient.

![image](https://user-images.githubusercontent.com/15224019/173897686-d59dfaad-7f21-4430-b522-df51385b7bbf.png)

**Comment by rannmann** [comment]
Well done!

**Comment by aritchie05** [comment]
@rannmann I believe the issue should auto-close when the commit is merged into the default branch (master). I am curious if it works like that
