### ISSUE TITLE
Self-hosting instructions

### ISSUE THREAD

**Issue by Dave247** [aritchie05/EcoCraftingTool#59]
Something I've been thinking about for a good while is how useful the publicly hosted website is, but how it lacks the ability to have any modified recipes. Being an open source project I've been thinking of trying to run a self-hosted solution of the project,but my experience is limited where I need to rely on some kind of guide, however sparse it may be in order to get me started and I can always use Google to fill in the rest.

The instructions given in the readme only while I could follow them, seem to account for how to build the site from source for a development environment and not a hosted/usable one. While I don't ask or expect to have a detailed step by step guide as I imagine it to be a complex process, at the very least an outline of what dependencies would be required as I could then likely figure out the rest for myself.

**Comment by aritchie05** [comment]
Hey @Dave247 there are a lot of ways to deploy to a web server. Fundamentally you can do it the old fashioned way, which involves building the app using the command `ng build --prod` in a console, which will build all the source files into the dist folder, and then you deploy those files to your own server. 

However, nowadays there are a lot of ways to connect the GitHub repo directly to a deployment pipeline (Vercel, Heroku, etc.) and have that handle everything. You could make your own fork for that.

**Comment by Dave247** [comment]
Thanks for the reply. A part of it is also an excuse and reason to have some fun and experience getting it all set up. Automating it would also be an interesting thing to try once I'm confident with it.

I suppose my main query then really boils down to, aside from the obvious (like Apache), is there any specific/different/unusual things needed to host this, or is it all self-contained within the repo?

**Comment by aritchie05** [comment]
Once you build the project files into the dist directory, you just need a web server and you can deploy it.

**Comment by Dave247** [comment]
> Once you build the project files into the dist directory, you just need a web server and you can deploy it.

Thanks, time for me to have fun building and deploying it then!
