### ISSUE TITLE
inputs missing

### ISSUE THREAD

**Issue by GabTrafalgar** [aritchie05/EcoCraftingTool#79]
Hello. First of all thank you for this amazing tool. I noticed that an item is missing in the inputs of the industry profession. Steel plate does not appear in the inputs so I wonder if the output calculations are correct. Thank you for taking the time to work on this tool. Merry Christmas to you :)

**Comment by GabTrafalgar** [comment]
[EDIT] I realize that in the industry profession, steel gear does not appear in the inputs either...

**Comment by aritchie05** [comment]
Thanks, I will take a look

**Comment by aritchie05** [comment]
@GabTrafalgar they don't appear in inputs list because they are outputs of the skill, so the output price is used for further calculations. If you remove them from outputs list, they will appear in the inputs list. You can just set the Steel Bar price and see how the corresponding prices change

**Comment by GabTrafalgar** [comment]
@aritchie05 Thank you for your quick response to my query. I was unaware of the existence of this list movement. It makes more sense now. Thank you for your explanation. Once again I wish you a Merry Christmas.
