### ISSUE TITLE
Table does not update correctly and messes up pricing

### ISSUE THREAD

**Issue by RumbleballTheReal** [aritchie05/EcoCraftingTool#86]
Hey, I played the first time with the tool to calculate pricing for Fiberglass (Glassworks).

What I did was go from left to right: Upgrades->Input material. I then messed with the upgrade by removing them to see what influence there is. Put the upgrade back in and change input prices. Now fiberglass did not update correctly. When putting Sand up to 10 (which is very important for Fiberglas), Fiberglass still showed with 1.4 for my calculation. 

I assume this is a general problem, not only to Fiberglass.

That means that calculation seems to be influenced by what you do at what point. That should not be the case. If anything updates -> Run the whole calculation again

**Comment by aritchie05** [comment]
@RumbleballTheReal can you post some screenshots of what you are seeing? I am not able to reproduce this:

![image](https://user-images.githubusercontent.com/15224019/227824704-cd25424c-70df-437c-bad9-6ad32e73e0c1.png)
![image](https://user-images.githubusercontent.com/15224019/227824663-265a12e6-f928-47ea-870c-b2e200c8a9ad.png)
