### ISSUE TITLE
Infinite loop here when removing table with unmet dependencies

### ISSUE THREAD

**Issue by ankemp** [aritchie05/EcoCraftingTool#88]
https://github.com/aritchie05/EcoCraftingTool/blob/d0d747d552b9890af2f9e2b485b882a442422434/src/app/crafting-parent/crafting-parent.component.ts#L605

Steps to recreate:
- Add skill: Smelting.
- Remove Blast furnance
- Remove bloomery
Crash occures.

Think its related to unmet item dependency. Probably need to switch from single array of items, to dependency tree or track array of item dependencies in each item to check if they exist in the items array, if they dont skip (or dont try to recalc)

**Comment by aritchie05** [comment]
Thanks for reporting, this issue was introduced in the last patch due to performance changes that were not fully tested. Reverted for now.
