### ISSUE TITLE
Possible error in pricing.

### ISSUE THREAD

**Issue by cypherwulfe** [aritchie05/EcoCraftingTool#91]
I am trying to use the calculator for my cooking store on a server. Trying to calculate specifically the cost of Vegetable soup. 

![soup](https://github.com/aritchie05/EcoCraftingTool/assets/134646269/eb9b8815-ab42-4435-9136-47014f7df36a)

It makes no logical sense for the soup to cost less than the medley. 

Also, the only way to get the full benefit of the module and skill, is to do a run of 100 of the items. Is it possible to add the ability to select how many of the item you want to make, and give the individual cost of each item?

**Comment by cypherwulfe** [comment]
I noticed this problem does not occur for no module, or 1-2 module. It only starts happening at module 3 and higher.

**Comment by aritchie05** [comment]
With an AU3 reducing ingredients by 40%, one vegetable soup costs .6 medley and .6 vegetable stock. How does it not make sense for a soup to cost less than a medley? One soup uses less than one medley so it is perfectly reasonable with enough efficiency.

**Comment by cypherwulfe** [comment]
If one vegetable soup takes .6 medley, and .6 stock, that is a total of 1.2 medleys to make. So one soup uses more than 1 medley to make.

**Comment by cypherwulfe** [comment]
You know what, your right, I am sorry.
