### ISSUE TITLE
Eco Calc

### ISSUE THREAD

**Issue by Oizotv** [aritchie05/EcoCraftingTool#98]
hi how we can change the eco calc version from 10.0.0 to 9.7.11 becaus the recipes are diffrent and its useless for the server now, pleas help and thanks

**Comment by aritchie05** [comment]
I updated the main site to stay on 9.7.11. Version 10.0 can now be accessed through the footer link at a separate url.

![image](https://github.com/aritchie05/EcoCraftingTool/assets/15224019/e92848f0-5c55-4b92-82ad-388de6cf6bbb)
